import {
    CommandButtonTextPipe,
    ExpireStatusPipe,
    LatestModifyDesPipe,
    RemoveMd5Pipe,
    StrategyNamePipe,
    TemplateNamePipe,
    VariableToSelectListPipe,
    VariableTypeNamePipe,
    VariableTypePipe,
    VariableValuePipe,
    CategoryNamePipe,
    ProgramLanguagePipe,
    CategoryColorPipe,
} from './strategy.pipe';

export const PIPES = [
    CommandButtonTextPipe,
    ExpireStatusPipe,
    LatestModifyDesPipe,
    RemoveMd5Pipe,
    StrategyNamePipe,
    TemplateNamePipe,
    VariableToSelectListPipe,
    VariableToSelectListPipe,
    VariableTypeNamePipe,
    VariableTypePipe,
    VariableValuePipe,
    CategoryNamePipe,
    ProgramLanguagePipe,
    CategoryColorPipe,
];
